### ISSUE TITLE
Expand options for `route_dir`

### ISSUE THREAD

**Issue by sitraka-hq** [sitraka-hq/hapi-auto-route#20]
There are 3 possibilities:

- Force user to set the `route_dir` option
- Make `route_dir` required and make it defaults to `routes`

`route_dir` can accept an array of directories where routes config can be loaded.

**Comment by OneHoopyFrood** [comment]
What is the alternative? However, it might be good to make it an array, so it can take multiple root directories. I could use this use case in one of my own projects.

**Comment by OneHoopyFrood** [comment]
Shall I take the thumbsup as a "go ahead?" If so, I'll mark this as an enhancement.

**Comment by sitraka-hq** [comment]
You can go ahead. Apart from that, I think that it's important to make route prefix configurable for each directory.

**Comment by OneHoopyFrood** [comment]
We still need to implement configurable prefix per directory.

**Comment by OneHoopyFrood** [comment]
I can't update the npm package. Would you mind doing the release @sitraka-hq ?

**Comment by OneHoopyFrood** [comment]
Also, did you happen to do some testing? I would like an independent party to verify it works properly.

**Comment by OneHoopyFrood** [comment]
Found some disfunction. Testing and correcting. Undid the PR for now. Will update and re-submit.

**Comment by OneHoopyFrood** [comment]
Ignore that ^
Discovered the revert PR function too late. I did a reset on the master branch and force pushed. Won't do that again in the future, sorry.

**Comment by sitraka-hq** [comment]
> 
> 
> I can't update the npm package. Would you mind doing the release @sitraka-hq ?

This functionality will be release with the #22.

**Comment by sitraka-hq** [comment]
I tested your code and it was ok! I restored your change in #23. I also profited to update some dependencies.

I think that everything is ok now!

**Comment by OneHoopyFrood** [comment]
Oh, it does def have some issues. I tried it out in a project and it fell apart. I've since worked it out though. I'll be making a new push today.
